name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-preview:
    name: Delete Preview Environment
    runs-on: ubuntu-latest

    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DEV }}" | base64 --decode > ~/.kube/config

      - name: Delete Helm release and namespace
        run: |
          RELEASE_NAME=smart-content-pr-${{ github.event.pull_request.number }}
          NAMESPACE=smartcms-pr-${{ github.event.pull_request.number }}

          helm uninstall $RELEASE_NAME --namespace $NAMESPACE || echo "Helm release not found"
          kubectl delete namespace $NAMESPACE || echo "Namespace not found"
