spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/smartcms}
smartai:
  api:
    url: http://localhost:8082/api/v1/ai
smartmedia:
  api:
    url: http://localhost:8083/api/v1/media