name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-and-test:
    name: Build & Test with Gradle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'gradle.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Check for required secrets
        run: |
          if [ -z "${{ secrets.USERNAME_GITHUB }}" ] || [ -z "${{ secrets.TOKEN_GITHUB }}" ]; then
            echo "Missing required secrets: USERNAME_GITHUB or TOKEN_GITHUB"
            exit 1
          fi

      - name: Setup gradle.properties
        run: |
          mkdir -p ~/.gradle
          echo "gpr.user=${{ secrets.USERNAME_GITHUB }}" >> ~/.gradle/gradle.properties
          echo "gpr.key=${{ secrets.TOKEN_GITHUB }}" >> ~/.gradle/gradle.properties
          echo "sonar.gradle.skipCompile=true" >> ~/.gradle/gradle.properties

      - name: Run Gradle build
        run: ./gradlew clean build --no-configuration-cache